#!/bin/bash
code --install-extension aaron-bond.better-comments
code --install-extension antfu.smart-clicks
code --install-extension aprilandjan.ascii-tree-generator
code --install-extension BazelBuild.vscode-bazel
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.path-intellisense
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension debens.sort-js-object
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension GitHub.copilot
code --install-extension golang.go
code --install-extension GraphQL.vscode-graphql
code --install-extension hashicorp.terraform
code --install-extension hilleer.yaml-plus-json
code --install-extension miclo.sort-typescript-imports
code --install-extension mintlify.document
code --install-extension mrmlnc.vscode-attrs-sorter
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-pg
code --install-extension nrwl.angular-console
code --install-extension PascalReitermann93.vscode-yaml-sort
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension richie5um2.vscode-sort-json
code --install-extension robertoachar.vscode-essentials-snippets
code --install-extension SimonSiefke.svg-preview
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Tchoupinax.tilt
code --install-extension timonwong.shellcheck
code --install-extension Tyriar.sort-lines
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wix.vscode-import-cost
