#!/bin/bash
codium --install-extension aaron-bond.better-comments
codium --install-extension aprilandjan.ascii-tree-generator
codium --install-extension BazelBuild.vscode-bazel
codium --install-extension bungcip.better-toml
codium --install-extension christian-kohler.path-intellisense
codium --install-extension DavidAnson.vscode-markdownlint
codium --install-extension debens.sort-js-object
codium --install-extension ecmel.vscode-html-css
codium --install-extension EditorConfig.EditorConfig
codium --install-extension esbenp.prettier-vscode
codium --install-extension firefox-devtools.vscode-firefox-debug
codium --install-extension golang.go
codium --install-extension GraphQL.vscode-graphql
codium --install-extension hashicorp.terraform
codium --install-extension hilleer.yaml-plus-json
codium --install-extension miclo.sort-typescript-imports
codium --install-extension mrmlnc.vscode-attrs-sorter
codium --install-extension ms-azuretools.vscode-docker
codium --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
codium --install-extension mtxr.sqltools
codium --install-extension mtxr.sqltools-driver-pg
codium --install-extension nrwl.angular-console
codium --install-extension PascalReitermann93.vscode-yaml-sort
codium --install-extension redhat.vscode-commons
codium --install-extension redhat.vscode-yaml
codium --install-extension richie5um2.vscode-sort-json
codium --install-extension robertoachar.vscode-essentials-snippets
codium --install-extension SimonSiefke.svg-preview
codium --install-extension streetsidesoftware.code-spell-checker
codium --install-extension Tchoupinax.tilt
codium --install-extension timonwong.shellcheck
codium --install-extension Tyriar.sort-lines
codium --install-extension vincaslt.highlight-matching-tag
codium --install-extension vscode-icons-team.vscode-icons
codium --install-extension wix.vscode-import-cost
